# Generated by Django 5.0.7 on 2024-07-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infinitive', models.CharField(max_length=30, unique=True)),
                ('past_simple', models.CharField(max_length=30, unique=True)),
                ('past_participle', models.CharField(max_length=30, unique=True)),
                ('definition', models.CharField(blank=True, max_length=366, unique=True)),
                ('translation', models.CharField(max_length=30, unique=True)),
                ('level', models.CharField(default='C2', max_length=2)),
            ],
        ),
    ]
