# Generated by Django 5.0.7 on 2024-07-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IrregularVerbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verbs',
            name='translation',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
