# Generated by Django 5.0.7 on 2024-07-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IrregularVerbs', '0002_alter_verbs_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verbs',
            name='definition',
            field=models.CharField(blank=True, max_length=366),
        ),
    ]
